
# prompt global settings
########################################

format = "$all"

# Module settings:

[username]
disabled = false
show_always = true
style_user = 'white bold'
style_root = 'red bold'

[character]
success_symbol = '[➜](bold green) '
error_symbol = '[✗](bold red) '

[memory]
disabled = false

[sudo]
disabled = false
